[package]
name = "datacleaning"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.5"
tokio = { version = "1.38.0", features = ["full"] }
neo4rs = "0.6.0"
csv = "1.3.0"
serde = "1.0.203"
serde_derive = "1.0.203"
xml5ever = "0.18.1"
